// ============================================================
// REAL CUTINS - the four parallax layers of each friend's
// collection screen, front to back. Generated by
// tools/cutins/accept.py. Do not hand-edit.
//
// A friend missing from here falls back to the code-drawn
// placeholder layers in core/art.js.
// ============================================================

const REAL_CUTINS = {

};
