// ============================================================
// REAL SPECIALS: the special attack screens' parallax layers, four
// per friend: index 0 the friend doing their special, 3 the far
// layer. GENERATED by tools/specials/accept.py (speciallib.wire),
// never edited by hand. A friend appears here only once all four
// of their layers exist.
// ============================================================

const REAL_SPECIALS = {
};
